name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Generate lock file if missing
        run: |
          if [ ! -f package-lock.json ]; then
            echo "🔧 package-lock.json not found. Creating..."
            npm install --package-lock-only
          fi

      - name: Install dependencies
        run: npm install

      - name: Run Type Check
        run: npm run type-check

      - name: Run Cypress tests
        run: npx cypress run --component

      - name: Upload Cypress videos (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos