name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/included:13.7.3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Start server and run Cypress test
        run: npx start-server-and-test start-server http://127.0.0.1:8080 "cypress run --spec cypress/e2e/example_spec.cy.js"